### PR TITLE
Change TO_DATE to tomorrow (exclusive) for both metrics

### LINKED ISSUE #63: Update action missing latest runs?
The "Update gh-pages" action last ran on 27 Oct 2021, 13:27 BST, and produced https://github.com/Ecosystem-Infra/wpt-results-analysis/commit/4722ba4811e0d66d816cdc72c9ee8400d71b8377

However, the only seems to have picked up runs to 2021-10-25, and not any of the more recent runs on wpt.fyi, especially for stable where we had our first Safari 15 run in that intervening period: https://wpt.fyi/runs?label=master&label=stable&max-count=100&from=2021-10-21T00%3A00&product=chrome&product=firefox&product=safari&aligned

### PR DESCRIPTION
**Pull request by foolip**
Fixes https://github.com/Ecosystem-Infra/wpt-results-analysis/issues/63.

### CODE REVIEW

**Comment by foolip** [comment]
I'm testing this in https://github.com/Ecosystem-Infra/wpt-results-analysis/actions/runs/1563178221.

**Comment by foolip** [comment]
I have vetted the changes by looking at `git diff origin/gh-pages origin/end-tomorrow-test-deploy` and I looks good to me. The Compat 2021 scores won't change as a result of this, because even though there have been some improvements, it's not enough to cross over to the next integer. ([Flooring of each area to an integer between 0-20](https://github.com/web-platform-tests/wpt.fyi/blob/d300d57ec61682512f0a95876986a3722dbbeb94/webapp/components/compat-2021.js#L551-L553) means that one has to pass a 5% boundary for an individual area to see a 1% improvement in the overall score.)

**Comment by gsnedders** [comment]
Is the risk here that we change what runs we use for a given day? Like, do we currently use the first run of a given day, or the last run of a given day? IIRC, we currently go for the latter, whereas this will end up with us using the latest run at the time the script runs, right?

**Comment by foolip** [comment]
@gsnedders excellent hypothesis, I didn't think of that, and it could indeed be the original reason here.

We use some URL starting with https://wpt.fyi/api/runs?aligned=true&max-count=1 and that API returns runs in the same order as https://wpt.fyi/runs, newest first. So after a day has ended, we would indeed pick the latest aligned run for that day.

Maybe this is OK, but it will result in some churn in the stats files generated here.

To avoid this, we'd need to wait until something like 3 hours after UTC midnight before trying to generate stats for the previous day. @gsnedders do you think that would be fast enough to resolve https://github.com/Ecosystem-Infra/wpt-results-analysis/issues/63?

**Comment by gsnedders** [comment]
I actually mentioned that in https://github.com/Ecosystem-Infra/wpt-results-analysis/issues/63#issuecomment-971607380 😜

One option is we basically regenerate this once on the day based in midday figures, then amend them the following day; another is we could just go for the first aligned build of each day (though idk if we can get that so easily via the API?).

I think the 3 hour wait was much longer because sometimes we see longer delays before the daily runs start, plus the run time sometimes various a bit (at least historically).

**Comment by foolip** [comment]
Oops 😬

The maximum total delay is indeed much longer than 3 hours now, because there's a pipeline of scheduled jobs, and also the use of yesterday's date (exclusive!) should mean a 24-48 hour delay just from this step, depending on when in the day the job runs.

**Pull request closed without merging**
